behaviors:
  Brain:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 20000
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 60000
    time_horizon: 1000
    summary_freq: 20000
    threaded: true
environment_parameters:
  maze_rows: 3.0
  maze_cols: 3.0
  target_x: 0
  target_z: 0
  agent_x: 0
  agent_z: 0
  random_agent: 1
  random_target: 1