behaviors:
  Brain:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 24000
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 512
    threaded: true
environment_parameters:
  maze_rows: 3.0
  maze_cols: 3.0
  target_x: 0
  target_z: 1
  agent_x: 0
  agent_z: 0
  random_agent: 0
  random_target: 0
