behaviors:
  Brain:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 256
      buffer_size: 20000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.5
      reward_signal_steps_per_update: 10.0
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000
    time_horizon: 1000
    summary_freq: 20000
    threaded: true
environment_parameters:
  maze_rows: 3.0
  maze_cols: 3.0
  target_x: 0
  target_z: 0
  agent_x: 0
  agent_z: 0
  random_agent: 1
  random_target: 1
