behaviors:
  Brain:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: linear
      batch_size: 512
      buffer_size: 300000
      buffer_init_steps: 10000
      tau: 0.005
      steps_per_update: 24.0
      save_replay_buffer: false
      init_entcoef: 0.6
      reward_signal_steps_per_update: 10.0
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 3.0
    keep_checkpoints: 1
    max_steps: 750000
    time_horizon: 128
    summary_freq: 20000
    threaded: true
environment_parameters:
  maze_rows: 3.0
  maze_cols: 3.0
  agent_x: 0.0
  agent_z: 0.0
  target_x: 2.0
  target_z: 2.0
  random_agent: 0.0
  random_target: 0.0
  maze_seed: 0